//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AssociationRegistry.Invitations.Api {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AssociationRegistry.Invitations.Api.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deze aanvraging kan niet meer aanvaard worden..
        /// </summary>
        public static string AanvaardenAanvraagOnmogelijk {
            get {
                return ResourceManager.GetString("AanvaardenAanvraagOnmogelijk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deze uitnodiging kan niet meer aanvaard worden..
        /// </summary>
        public static string AanvaardenUitnodigingOnmogelijk {
            get {
                return ResourceManager.GetString("AanvaardenUitnodigingOnmogelijk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deze aanvraging kan niet meer ingetrokken worden..
        /// </summary>
        public static string IntrekkenAanvraagOnmogelijk {
            get {
                return ResourceManager.GetString("IntrekkenAanvraagOnmogelijk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deze uitnodiging kan niet meer ingetrokken worden..
        /// </summary>
        public static string IntrekkenUitnodigingOnmogelijk {
            get {
                return ResourceManager.GetString("IntrekkenUitnodigingOnmogelijk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deze aanvraging kan niet meer geweigerd worden..
        /// </summary>
        public static string WeigerenAanvraagOnmogelijk {
            get {
                return ResourceManager.GetString("WeigerenAanvraagOnmogelijk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deze uitnodiging kan niet meer geweigerd worden..
        /// </summary>
        public static string WeigerenUitnodigingOnmogelijk {
            get {
                return ResourceManager.GetString("WeigerenUitnodigingOnmogelijk", resourceCulture);
            }
        }
    }
}
