name: Main

on:
  push:
    branches: [ main ]
  workflow_dispatch:

concurrency: CI
jobs:

  analyze-code:
    name: Analyze Code
    uses: informatievlaanderen/build-pipeline/.github/workflows/analyze-code.yml@main
    with:
      registry: association-registry-invitations
    secrets: inherit

  decide-release-version:
    name: Decide Next Version
    uses: informatievlaanderen/build-pipeline/.github/workflows/set-release-version.yml@main
    secrets: inherit
    
  set-release-version:
    name: Set Release Version
    runs-on: ubuntu-latest
    needs: [ decide-release-version ]
    outputs:
      version: ${{ env.RELEASE_VERSION }}
    steps:
      - name: Check version
        shell: bash
        run: echo $SEMVER
        env:
          SEMVER: ${{ needs.set-release-version.outputs.version }}
  
  build-invitations-api:
    if: github.repository_owner == 'informatievlaanderen' && needs.set-release-version.outputs.version != 'none'
    name: Build Invitations Api
    runs-on: ubuntu-latest
    needs: [ set-release-version ]
    steps:
      - name: Check version
        shell: bash
        run: echo $SEMVER
        env:
          SEMVER: ${{ needs.set-release-version.outputs.version }}

      - name: Checkout Code
        uses: actions/checkout@v4
        
      - name: Parse repository name
        run: echo REPOSITORY_NAME=$(echo "$GITHUB_REPOSITORY" | awk -F / '{print $2}' | sed -e "s/:refs//") >> $GITHUB_ENV
        shell: bash

      - name: Run dependencies
        shell: bash
        run: |
          docker compose up -d
          
      - name: Restore paket packages
        id: cache-paket-restore
        uses: actions/cache/restore@v3
        with:
          path: |
            packages
            .paket/Paket.Restore.targets
          key: ${{ runner.os }}-paket-${{ hashFiles('paket.lock', '.paket/Paket.Restore.targets') }}

      - name: Create testresults directory
        run: mkdir -p testresults

      - name: Test via docker run
        shell: bash
        run: |
          docker run --network host --rm -v $(pwd):/app -w /app/ mcr.microsoft.com/dotnet/sdk:6.0.201 /bin/sh .github/build-scripts/run-tests-docker.sh AssociationRegistry.Invitations.Api.Tests

      - name: Set solution info
        shell: bash
        run: |
          docker run --network host -e CI_BUILD_NUMBER -e GIT_HASH --rm -v $(pwd):/app -w /app/ mcr.microsoft.com/dotnet/sdk:6.0.201 /bin/sh .github/build-scripts/set-solution-info.sh
        env:
          CI_BUILD_NUMBER: ${{ needs.set-release-version.outputs.version }}

      - name: Publish via docker run
        shell: bash
        run: |
          docker run --network host --rm -v $(pwd):/app -w /app/ mcr.microsoft.com/dotnet/sdk:6.0.201 /bin/sh .github/build-scripts/publish.sh AssociationRegistry.Invitations.Api

      - name: Build image
        shell: bash
        run: |
          .github/build-scripts/build-docker.sh AssociationRegistry.Invitations.Api invitations-api
        env:
          BUILD_DOCKER_REGISTRY: ${{ secrets.VBR_BUILD_DOCKER_REGISTRY_TST }}
          CI_BUILD_NUMBER: ${{ needs.set-release-version.outputs.version }}
      
      - name: Show images
        shell: bash
        run: docker images

      - name: Save Image
        if: needs.set-release-version.outputs.version != 'none'
        shell: bash
        run: docker image save $BUILD_DOCKER_REGISTRY/association-registry/invitations-api:$SEMVER -o ~/invitations-api.tar
        env:
          BUILD_DOCKER_REGISTRY: ${{ secrets.VBR_BUILD_DOCKER_REGISTRY_TST }}
          SEMVER: ${{ needs.set-release-version.outputs.version }}

      - name: Upload Api artifact
        if: needs.set-release-version.outputs.version != 'none'
        uses: actions/upload-artifact@v3
        with:
          name: invitations-api
          path: ~/invitations-api.tar

      - name: Shows logs ACM container
        if: ${{ failure() }}
        shell: bash
        run: |
          docker logs acm

      - name: Shows logs elasticsearch container
        if: ${{ failure() }}
        shell: bash
        run: |
          docker logs elasticsearch

      - name: Shows logs wiremock container
        if: ${{ failure() }}
        shell: bash
        run: |
          docker logs wiremock

      - name: Shows logs db container
        if: ${{ failure() }}
        shell: bash
        run: |
          docker logs db

  build-invitations-archiver:
    if: github.repository_owner == 'informatievlaanderen' && needs.set-release-version.outputs.version != 'none'
    name: Build Invitations Archiver
    runs-on: ubuntu-latest
    needs: [ set-release-version ]
    steps:
      - name: Check version
        shell: bash
        run: echo $SEMVER
        env:
          SEMVER: ${{ needs.set-release-version.outputs.version }}

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Parse repository name
        run: echo REPOSITORY_NAME=$(echo "$GITHUB_REPOSITORY" | awk -F / '{print $2}' | sed -e "s/:refs//") >> $GITHUB_ENV
        shell: bash

      - name: Run dependencies
        shell: bash
        run: |
          docker compose up -d db

      - name: Restore paket packages
        id: cache-paket-restore
        uses: actions/cache/restore@v3
        with:
          path: |
            packages
            .paket/Paket.Restore.targets
          key: ${{ runner.os }}-paket-${{ hashFiles('paket.lock', '.paket/Paket.Restore.targets') }}

      - name: Create testresults directory
        run: mkdir -p testresults

      - name: Test via docker run
        shell: bash
        run: |
          docker run --network host --rm -v $(pwd):/app -w /app/ mcr.microsoft.com/dotnet/sdk:6.0.201 /bin/sh .github/build-scripts/run-tests-docker.sh AssociationRegistry.Invitations.Archiver.Tests

      - name: Set solution info
        shell: bash
        run: |
          docker run --network host -e CI_BUILD_NUMBER -e GIT_HASH --rm -v $(pwd):/app -w /app/ mcr.microsoft.com/dotnet/sdk:6.0.201 /bin/sh .github/build-scripts/set-solution-info.sh
        env:
          CI_BUILD_NUMBER: ${{ needs.set-release-version.outputs.version }}

      - name: Publish via docker run
        shell: bash
        run: |
          docker run --network host --rm -v $(pwd):/app -w /app/ mcr.microsoft.com/dotnet/sdk:6.0.201 /bin/sh .github/build-scripts/publish.sh AssociationRegistry.Invitations.Archiver

      - name: Build image
        shell: bash
        run: |
          .github/build-scripts/build-docker.sh AssociationRegistry.Invitations.Archiver invitations-archiver
        env:
          BUILD_DOCKER_REGISTRY: ${{ secrets.VBR_BUILD_DOCKER_REGISTRY_TST }}
          CI_BUILD_NUMBER: ${{ needs.set-release-version.outputs.version }}

      - name: Show images
        shell: bash
        run: docker images

      - name: Save Image
        if: needs.set-release-version.outputs.version != 'none'
        shell: bash
        run: docker image save $BUILD_DOCKER_REGISTRY/association-registry/invitations-archiver:$SEMVER -o ~/invitations-archiver.tar
        env:
          BUILD_DOCKER_REGISTRY: ${{ secrets.VBR_BUILD_DOCKER_REGISTRY_TST }}
          SEMVER: ${{ needs.set-release-version.outputs.version }}

      - name: Upload Archiver artifact
        if: needs.set-release-version.outputs.version != 'none'
        uses: actions/upload-artifact@v3
        with:
          name: invitations-archiver
          path: ~/invitations-archiver.tar

      - name: Shows logs db container
        if: ${{ failure() }}
        shell: bash
        run: |
          docker logs db

  release:
    if: needs.set-release-version.outputs.version != 'none'
    name: Semantic Release
    runs-on: ubuntu-latest
    needs: 
      - build-invitations-api
      - build-invitations-archiver
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Cache NPM
        uses: informatievlaanderen/build-pipeline/.github/actions/cache-npm@main

      - name: Parse repository name
        run: echo REPOSITORY_NAME=$(echo "$GITHUB_REPOSITORY" | awk -F / '{print $2}' | sed -e "s/:refs//") >> $GITHUB_ENV
        shell: bash
        
      - name: Setup NodeJS
        uses: informatievlaanderen/build-pipeline/.github/actions/setup-nodejs@main

      - name: Setup Python
        uses: informatievlaanderen/build-pipeline/.github/actions/setup-python@main

      - name: Generate Token
        id: generate_token   # Add an ID to this step for reference
        run: node .github/build-scripts/generate-token.js
        env:
          APP_ID: ${{ secrets.MYBOT_APP_ID }}
          PRIVATE_KEY: ${{ secrets.MYBOT_PRIVATE_KEY }}

      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          token: ${{ steps.generate_token.outputs.installationToken  }}

      - name: Install NPM dependencies
        shell: bash
        run: npm install --legacy-peer-deps

      - name: Run Semantic Release
        shell: bash
        run: npx semantic-release
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ steps.generate_token.outputs.installationToken  }}
          GIT_COMMIT: ${{ github.sha }}
          GIT_USERNAME: ${{ steps.generate_token.outputs.installationToken }}
          GIT_AUTHOR_NAME: ${{ secrets.VBR_GIT_USER }}
          GIT_COMMITTER_NAME: ${{ secrets.VBR_GIT_USER }}
          GIT_EMAIL: ${{ secrets.VBR_GIT_EMAIL }}
          GIT_AUTHOR_EMAIL: ${{ secrets.VBR_GIT_EMAIL }}
          GIT_COMMITTER_EMAIL: ${{ secrets.VBR_GIT_EMAIL }}
          BUILD_DOCKER_REGISTRY: ${{ secrets.VBR_BUILD_DOCKER_REGISTRY_TST }}

  publish_to_atlassian:
    if: needs.set-release-version.outputs.version != 'none'
    needs: 
      - set-release-version
      - release
    name: Publish to Atlassian
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Parse repository name
        run: echo REPOSITORY_NAME=$(echo "$GITHUB_REPOSITORY" | awk -F / '{print $2}' | sed -e "s/:refs//") >> $GITHUB_ENV
        shell: bash

      - name: Cache Paket
        uses: actions/cache@v3
        env:
          cache-name: cache-paket
        with:
          path: packages
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('paket.lock') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-

      - name: Cache Python
        uses: actions/cache@v3
        env:
          cache-name: cache-pip
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-build-${{ env.cache-name }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Python dependencies
        shell: bash
        run: |
          python -m pip install --upgrade pip
          pip install requests markdown argparse

      - name: Publish to Confluence
        if: needs.set-release-version.outputs.version != 'none'
        shell: bash
        run: ./packages/Be.Vlaanderen.Basisregisters.Build.Pipeline/Content/ci-confluence.sh
        env:
          CONFLUENCE_TITLE: ${{ env.REPOSITORY_NAME }}
          CONFLUENCE_USERNAME: ${{ secrets.VBR_CONFLUENCE_USER }}
          CONFLUENCE_PASSWORD: ${{ secrets.VBR_CONFLUENCE_PASSWORD }}

      - name: Create Jira Release
        if: needs.set-release-version.outputs.version != 'none'
        shell: bash
        run: ./packages/Be.Vlaanderen.Basisregisters.Build.Pipeline/Content/ci-jira.sh
        env:
          CONFLUENCE_TITLE: ${{ env.REPOSITORY_NAME }}
          CONFLUENCE_USERNAME: ${{ secrets.VBR_CONFLUENCE_USER }}
          CONFLUENCE_PASSWORD: ${{ secrets.VBR_CONFLUENCE_PASSWORD }}
          JIRA_PREFIX: Association-Invitations
          JIRA_PROJECT: OR
          JIRA_VERSION: ${{ needs.set-release-version.outputs.version }}

  push_images_to_test:
    if: needs.set-release-version.outputs.version != 'none'
    needs: 
      - set-release-version
      - release
    name: Push images to Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        services:
          [
            'invitations-api',
            'invitations-archiver',
          ]
    steps:
      - name: Configure AWS credentials (Test)
        if: needs.set-release-version.outputs.version != 'none'
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.VBR_AWS_ACCESS_KEY_ID_TST }}
          aws-secret-access-key: ${{ secrets.VBR_AWS_SECRET_ACCESS_KEY_TST }}
          aws-region: ${{ secrets.VBR_AWS_REGION_PRD }}

      - name: Login to Amazon ECR (Test)
        if: needs.set-release-version.outputs.version != 'none'
        uses: aws-actions/amazon-ecr-login@v2.0.1

      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: ${{matrix.services}}
          path: ~/

      - name: Load image
        shell: bash
        run: docker image load -i ~/${{matrix.services}}.tar

      - name: Push docker images to ECR Test
        if: needs.set-release-version.outputs.version != 'none'
        shell: bash
        run: |
          echo $SEMVER
          docker push $BUILD_DOCKER_REGISTRY/association-registry/${{matrix.services}}:$SEMVER
        env:
          BUILD_DOCKER_REGISTRY: ${{ secrets.VBR_BUILD_DOCKER_REGISTRY_TST }}
          SEMVER: ${{ needs.set-release-version.outputs.version }}
          WORKSPACE: ${{ github.workspace }}

  push_images_to_staging:
    if: needs.set-release-version.outputs.version != 'none'
    needs:
      - set-release-version
      - release
    name: Push images to Staging
    runs-on: ubuntu-latest
    strategy:
      matrix:
        services:
          [
            'invitations-api',
            'invitations-archiver',
          ]
    steps:
      - name: Configure AWS credentials (Staging)
        if: needs.set-release-version.outputs.version != 'none'
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.VBR_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.VBR_AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.VBR_AWS_REGION_PRD }}

      - name: Login to Amazon ECR (Staging)
        if: needs.set-release-version.outputs.version != 'none'
        uses: aws-actions/amazon-ecr-login@v2.0.1

      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: ${{matrix.services}}
          path: ~/

      - name: Load image
        shell: bash
        run: docker image load -i ~/${{matrix.services}}.tar

      - name: Push docker images to ECR Staging
        if: needs.set-release-version.outputs.version != 'none'
        shell: bash
        run: |
          echo $SEMVER
          docker tag $BUILD_DOCKER_REGISTRY_TST/association-registry/${{matrix.services}}:$SEMVER $BUILD_DOCKER_REGISTRY/association-registry/${{matrix.services}}:$SEMVER
          docker push $BUILD_DOCKER_REGISTRY/association-registry/${{matrix.services}}:$SEMVER
        env:
          BUILD_DOCKER_REGISTRY_TST: ${{ secrets.VBR_BUILD_DOCKER_REGISTRY_TST }}
          BUILD_DOCKER_REGISTRY: ${{ secrets.VBR_BUILD_DOCKER_REGISTRY }}
          SEMVER: ${{ needs.set-release-version.outputs.version }}
          WORKSPACE: ${{ github.workspace }}
          
  deploy_test:
    if: needs.set-release-version.outputs.version != 'none'
    needs: 
      - set-release-version
      - release
      - push_images_to_test
    name: Deploy to Test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        services:
          [
            'association-registry-invitations-api',
            'association-registry-invitations-archiver',
          ]
    steps:
      - name: debug_output
        shell: bash
        run: |
          echo ${{ needs.set-release-version.outputs.version }}
      - name: CD
        if: needs.set-release-version.outputs.version != 'none'
        env:
          BUILD_URL: ${{ secrets.VBR_AWS_BUILD_API }}/${{matrix.services}}
          STATUS_URL: ${{ secrets.VBR_AWS_BUILD_STATUS_API }}/${{matrix.services}}
        uses: informatievlaanderen/awscurl-polling-action/polling-action@main
        with:
          environment: test
          version: ${{ needs.set-release-version.outputs.version }}
          status-url: $STATUS_URL
          deploy-url: $BUILD_URL
          access-key: ${{ secrets.VBR_AWS_BUILD_USER_ACCESS_KEY_ID }}
          secret-key: ${{ secrets.VBR_AWS_BUILD_USER_SECRET_ACCESS_KEY }}
          region: eu-west-1
          interval: 2
      - name: output
        shell: bash
        run: |
          echo build-uuid: ${{ steps.awscurl-polling-action.outputs.build-uuid }}
          echo Status: ${{ steps.awscurl-polling-action.outputs.status }}
          echo ${{ steps.awscurl-polling-action.outputs.final-message }}
