name: Manual Deploy To Production (IK4)

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version (format: x.xxx.x, ie: 1.221.1)'
        required: true

jobs:

  deploy_services_ik4:
    name: Deploy services to Production (IK4)
    environment: 'production_ik4'
    runs-on: 'ubuntu-latest'
    strategy:
      matrix:
        services:
          [
            'uitnodigingenapi'
          ]
    steps:
      - name: CD
        id: awscurl-polling-action
        env:
          BUILD_URL: ${{ secrets.VBR_AWS_BUILD_API }}/${{matrix.services}}/prd/deploy/v4
          STATUS_URL: ${{ secrets.VBR_AWS_BUILD_STATUS_API }}/${{matrix.services}}/prd/deploy/v4/status
        uses: informatievlaanderen/awscurl-polling-action/polling-action@deploy-v4
        with:
          environment: prd
          version: ${{ github.event.inputs.version }}
          status-url: $STATUS_URL
          deploy-url: $BUILD_URL
          access-key: ${{ secrets.VBR_AWS_BUILD_USER_ACCESS_KEY_ID_IK4 }}
          secret-key: ${{ secrets.VBR_AWS_BUILD_USER_SECRET_ACCESS_KEY_IK4 }}
          deploy-target: 'ecs'
          domain: 'verenigingsregister'
          project: 'verenigingsregister'
          application: ${{matrix.services}}
          interval: 2
      - name: output
        shell: bash
        if: always()
        run: |
          echo build-uuid: ${{ steps.awscurl-polling-action.outputs.build-uuid }}
          echo Status: ${{ steps.awscurl-polling-action.outputs.status }}
          echo ${{ steps.awscurl-polling-action.outputs.final-message }}

  deploy_scheduled_tasks_ik4:
    name: Deploy scheduled tasks to Production (IK4)
    environment: 'production_ik4'
    runs-on: 'ubuntu-latest'
    strategy:
      matrix:
        services:
          [
            'uitnodigingenarchiver'
          ]
    steps:
      - name: CD
        id: awscurl-polling-action
        env:
          BUILD_URL: ${{ secrets.VBR_AWS_BUILD_API }}/${{matrix.services}}/prd/deploy/v4
          STATUS_URL: ${{ secrets.VBR_AWS_BUILD_STATUS_API }}/${{matrix.services}}/prd/deploy/v4/status
        uses: informatievlaanderen/awscurl-polling-action/polling-action@deploy-v4
        with:
          environment: prd
          version: ${{ github.event.inputs.version }}
          status-url: $STATUS_URL
          deploy-url: $BUILD_URL
          access-key: ${{ secrets.VBR_AWS_BUILD_USER_ACCESS_KEY_ID_IK4 }}
          secret-key: ${{ secrets.VBR_AWS_BUILD_USER_SECRET_ACCESS_KEY_IK4 }}
          domain: 'verenigingsregister'
          project: 'verenigingsregister'
          deploy-target: 'ecs'
          application: ${{matrix.services}}
          interval: 2
      - name: output
        shell: bash
        if: always()
        run: |
          echo build-uuid: ${{ steps.awscurl-polling-action.outputs.build-uuid }}
          echo Status: ${{ steps.awscurl-polling-action.outputs.status }}
          echo ${{ steps.awscurl-polling-action.outputs.final-message }}
