name: Manual Deploy To Test (IK4)

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version (format: x.xxx.x, ie: 1.221.1)'
        required: true

jobs:

  deploy_services_ik4:
    if: needs.release.outputs.version != 'none'
    name: Deploy services to Test (IK4)
    environment: 'test_ik4'
    runs-on: 'ubuntu-latest'
    strategy:
      matrix:
        services:
          [
            'uitnodigingenapi'
          ]
    steps:
      - name: debug_output
        shell: bash
        run: |
          echo ${{ needs.release.outputs.version }}
      - name: CD
        if: needs.release.outputs.version != 'none'
        env:
          BUILD_URL: ${{ secrets.VBR_AWS_BUILD_API }}/${{matrix.services}}
          STATUS_URL: ${{ secrets.VBR_AWS_BUILD_STATUS_API }}/${{matrix.services}}
        uses: informatievlaanderen/awscurl-polling-action/polling-action@main
        with:
          environment: 'test'
          version: ${{ needs.release.outputs.version }}
          status-url: $STATUS_URL
          deploy-url: $BUILD_URL
          access-key: ${{ secrets.VBR_AWS_BUILD_USER_ACCESS_KEY_ID_IK4 }}
          secret-key: ${{ secrets.VBR_AWS_BUILD_USER_SECRET_ACCESS_KEY_IK4 }}
          region: 'eu-west-1'
          deploy-target: 'ecs_service'
          interval: 2
      - name: output
        shell: bash
        if: always()
        run: |
          echo build-uuid: ${{ steps.awscurl-polling-action.outputs.build-uuid }}
          echo Status: ${{ steps.awscurl-polling-action.outputs.status }}
          echo ${{ steps.awscurl-polling-action.outputs.final-message }}

  deploy_scheduled_tasks_ik4:
    if: needs.release.outputs.version != 'none'
    name: Deploy scheduled tasks to Test (IK4)
    environment: 'test_ik4'
    runs-on: 'ubuntu-latest'
    strategy:
      matrix:
        services:
          [
            'uitnodigingenarchiver'
          ]
    steps:
      - name: debug_output
        shell: bash
        run: |
          echo ${{ needs.release.outputs.version }}
      - name: CD
        if: needs.release.outputs.version != 'none'
        env:
          BUILD_URL: ${{ secrets.VBR_AWS_BUILD_API }}/${{matrix.services}}
          STATUS_URL: ${{ secrets.VBR_AWS_BUILD_STATUS_API }}/${{matrix.services}}
        uses: informatievlaanderen/awscurl-polling-action/polling-action@main
        with:
          environment: 'test'
          version: ${{ needs.release.outputs.version }}
          status-url: $STATUS_URL
          deploy-url: $BUILD_URL
          access-key: ${{ secrets.VBR_AWS_BUILD_USER_ACCESS_KEY_ID_IK4 }}
          secret-key: ${{ secrets.VBR_AWS_BUILD_USER_SECRET_ACCESS_KEY_IK4 }}
          region: 'eu-west-1'
          deploy-target: 'ecs_scheduled_task'
          interval: 2
      - name: output
        shell: bash
        if: always()
        run: |
          echo build-uuid: ${{ steps.awscurl-polling-action.outputs.build-uuid }}
          echo Status: ${{ steps.awscurl-polling-action.outputs.status }}
          echo ${{ steps.awscurl-polling-action.outputs.final-message }}
